name: Build and test docker container for development

on:
  pull_request:
    branches:
      - main
    paths:
      - 'garmin_fetch.py'
      - 'compose-example.yml'
      - 'requirements.txt'
      - 'Dockerfile'

env:
  REGISTRY: docker.io
  IMAGE_NAME: thisisarpanghosh/garmin-fetch-data

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image (multi-arch)
        run: docker buildx build --platform linux/amd64 --load -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test the Docker image
        run: docker compose -f compose-example.yml up -d
